# Generated by Django 3.1 on 2020-11-23 03:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('LVQ', 'Livros, Revistas e Quadrinhos'), ('TEC', 'Tecnologia'), ('CEE', 'Casa e Eletrodomésticos'), ('EEL', 'Esporte e Lazer'), ('MBA', 'Moda, Bijuterias e Acessórios'), ('FEM', 'Ferramentas e Máquinas'), ('BRI', 'Brinquedos Infantis'), ('PET', 'Pets')], max_length=3)),
                ('info', markdownx.models.MarkdownxField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrocoPor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exemplo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exemplo_id', to='products.products')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produto_id', to='products.products')),
            ],
        ),
    ]
